name:                servant-kotlin
version:             0.1.0.0
homepage:            https://github.com/matsubara0507/servant-kotlin#readme
license:             BSD3
author:              MATSUBARA Nobutada
maintainer:          example@example.com
copyright:           2017 MATSUBARA Nobutada
category:            Web
extra-source-files:
  - README.md

ghc-options: -Wall

dependencies:
  - base >= 4.7 && < 5
  - containers >= 0.5.7 && < 0.6.0
  - directory >= 1.3 && < 1.4
  - formatting >= 6.2.4 && < 6.3
  - lens >= 4.15 && < 4.16
  - servant >= 0.9 && < 0.12
  - servant-foreign >= 0.9 && < 0.12
  - text >= 1.2.2 && < 1.2.3
  - time >= 1.6 && < 1.9
  - wl-pprint-text >= 1.1 && < 1.2

library:
  source-dirs: src
  exposed-modules:
    - Servant.Kotlin
    - Servant.Kotlin.Type
    - Servant.Kotlin.Internal.File
    - Servant.Kotlin.Internal.Foreign
    - Servant.Kotlin.Internal.Generate
  other-modules: []
  ghc-options: -fno-warn-orphans

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - src
      - test
    dependencies:
      - aeson >= 1.0 && < 1.3
      - hspec >= 2.4.1 && < 2.5
      - http-api-data >= 0.3.7 && < 0.3.8
