name:                servant-kotlin
version:             0.1.0.3
synopsis:            Automatically derive Kotlin class to query servant webservices
description:         See README at <https://github.com/matsubara0507/servant-kotlin#readme>
homepage:            https://github.com/matsubara0507/servant-kotlin#readme
license:             MIT
author:              MATSUBARA Nobutada
maintainer:          MATSUBARA Nobutada
copyright:           2017-2018 MATSUBARA Nobutada
category:            Web
extra-source-files:
  - README.md

ghc-options: -Wall

dependencies:
  - base >= 4.7 && < 5
  - containers >= 0.5.7 && < 0.6.0
  - directory >= 1.3 && < 1.4
  - formatting >= 6.2 && < 6.4
  - lens >= 4.15 && < 4.17
  - servant >= 0.9 && < 0.14
  - servant-foreign >= 0.9 && < 0.12
  - text >= 1.2 && < 1.3
  - time >= 1.6 && < 1.9
  - wl-pprint-text >= 1.1 && < 1.2

library:
  source-dirs: src

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - src
      - test
    dependencies:
      - aeson >= 1.0 && < 1.3
      - hspec >= 2.4.1 && < 2.5
      - http-api-data >= 0.3.7 && < 0.3.8

benchmarks:
  generate-test:
    main: example/Generater.hs
    dependencies:
      - aeson >= 1.0 && < 1.3
      - http-api-data >= 0.3.7 && < 0.3.8
      - servant-kotlin
      - shelly >= 1.6.8 && < 1.8
