name:                servant-kotlin
version:             0.1.0.0
homepage:            https://github.com/matsubara0507/servant-kotlin#readme
license:             BSD3
author:              MATSUBARA Nobutada
maintainer:          example@example.com
copyright:           2017 MATSUBARA Nobutada
category:            Web
extra-source-files:
  - README.md

ghc-options: -Wall

dependencies:
  - base >= 4.7 && < 5
  - containers
  - directory
  - formatting
  - lens
  - servant
  - servant-foreign
  - text
  - time
  - wl-pprint-text

library:
  source-dirs: src
  exposed-modules:
    - Servant.Kotlin
    - Servant.Kotlin.Type
    - Servant.Kotlin.Internal.File
    - Servant.Kotlin.Internal.Foreign
    - Servant.Kotlin.Internal.Generate
  other-modules: []
  ghc-options: -fno-warn-orphans

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - src
      - test
    dependencies:
      - aeson
      - hspec >=2.4.1 && <2.5
      - http-api-data
