name:                servant-kotlin
version:             0.1.0.0
homepage:            https://github.com/matsubara0507/servant-kotlin#readme
license:             BSD3
author:              MATSUBARA Nobutada
maintainer:          example@example.com
copyright:           2017 MATSUBARA Nobutada
category:            Web
extra-source-files:
  - README.md

ghc-options: -Wall

dependencies:
  - base >= 4.7 && < 5
  - containers
  - text
  - time

library:
  source-dirs: src
  exposed-modules:
    - Servant.Kotlin.Type
    - Servant.Kotlin.Internal.Generate
  other-modules: []
  ghc-options: -fno-warn-orphans
