resolver: nightly-2018-05-11
packages:
- .
extra-deps: []
# - servant-0.13
# - lens-4.16
# - http-types-0.12
# - servant-foreign-0.11
# - shelly-1.8.0
# - time-1.9.1
# - wl-pprint-text-1.2.0.0

flags: {}
extra-package-dbs: []
