resolver: nightly-2018-10-26
packages:
- .
extra-deps: []
# - aeson-1.4.0.0
# - servant-0.14.1
# - lens-4.17
# - http-types-0.12
# - servant-foreign-0.11
# - shelly-1.8.0
# - time-1.9.1
# - wl-pprint-text-1.2.0.0
# - containers-0.6.0.1

flags: {}
extra-package-dbs: []
