resolver: nightly-2018-04-15
packages:
- .
extra-deps:
- wl-pprint-text-1.1.1.1
- base-compat-0.10.1
- aeson-1.3.1.0
# - servant-0.13
# - lens-4.16
# - http-types-0.12
# - servant-foreign-0.11

flags: {}
extra-package-dbs: []
